### ISSUE TITLE
Link to 'nightly' build

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/libm2k#10]
Hi:
I know you are not yet ready apparently to put out an official release, but can you for right now add a link to the 'nightly' build on AppVeyor on the Read Me page?

Thanks

Doug

**Comment by AlexandraTrifan** [comment]
Hi, 

There is a status badge on the README page which links the appveyor build. I will also add a text to it.

-Alexandra

**Comment by AlexandraTrifan** [comment]
README has been updated with commit 1d1b22917eb8b252468c3544d52abe2762d52ce7 .
Also, there is a wiki page for libm2k. ( https://wiki.analog.com/libm2k )
