### ISSUE TITLE
Add macOS 10.15 (Catalina) builds

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libm2k#171]
I've been getting requests for Catalina builds since that is the main version macOS users are on. Travis-CI supports it.

**Comment by AlexandraTrifan** [comment]
Added Catalina builds with the following PR ( https://github.com/analogdevicesinc/libm2k/pull/178 ). 
The artifacts will appear in the next release.

**Comment by AlexandraTrifan** [comment]
Artifacts were added to the latest release: https://github.com/analogdevicesinc/libm2k/releases/tag/v0.3.0
