### ISSUE TITLE
Add Ubuntu 20.04 builds

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libm2k#172]
Request: https://ez.analog.com/adieducation/university-program/f/q-a/534396/libm2k-for-ubuntu-20

**Comment by AlexandraTrifan** [comment]
Added Ubuntu 20.04 builds with the following PR ( https://github.com/analogdevicesinc/libm2k/pull/178 ). 
The artifacts will appear in the next release.

**Comment by AlexandraTrifan** [comment]
Artifacts were added to the latest release : https://github.com/analogdevicesinc/libm2k/releases/tag/v0.3.0
