### ISSUE TITLE
Looping issue for output buffers not equal to a multiple of 4.

### ISSUE THREAD

**Issue by jaxankey** [analogdevicesinc/libm2k#174]
When the output buffer length is not a multiple of 4, the frequency I measure is quite far from what I sent, due to a hiccup in the loop points. Below is a minimal working example, where you can fiddle with the variable `No` to see how it affects the continuity of the waveform. The script creates an output waveform with an integer number of oscillations, sends it to the output, and acquires 100 ms of data. It then plots the measured waveform, the expected waveform, and (most helpful!) the sum of the two. 

```Python
import libm2k, pylab, numpy, time

# Set the output buffer size (No), and rate
No      = 282      # <-------- This needs to be a multiple of 4 to work right
ao_rate = 75000.0

# Get a frequency with an integer number of cycles in this buffer.
f = ao_rate/No * 8   
print('Frequency =', f)

# Get the first m2k name, open it, and run the calibration
name = libm2k.getAllContexts()[0]
m2k = libm2k.m2kOpen(name).toM2k()
m2k.calibrate()

# Enable the outputs and set the rates.
ao = m2k.getAnalogOut()
ao.enableChannel(0, True)
ao.enableChannel(1, True)
ao.setSampleRate(0, ao_rate)
ao.setSampleRate(1, ao_rate)

# Create the sinusoidal waveform
ns = numpy.linspace(0,No-1,No) # List of integers
ts = ns/ao_rate                # Time array
v1 = numpy.sin(2*numpy.pi*f*ts) # f fits an integer number of periods into this buffer

# Send the same waveform to the outputs
ao.push([v1,v1]) # Default is cyclic

# Enable the first input channel and configure
ai_rate = 100000.0
ai = m2k.getAnalogIn()
ai.enableChannel(0, True)
ai.enableChannel(1, True)
ai.setSampleRate(ai_rate)
ai.setRange(0, libm2k.HIGH_GAIN)
ai.setRange(1, libm2k.HIGH_GAIN)

# Set the timeout (1 sec) so it collects without trigger
m2k.setTimeout(1000)

# Let it settle
time.sleep(0.1)

# Get 100 ms of data
Ni = int(0.1*ai_rate)
y1, y2 = ai.getSamples(Ni)

# Get the time-domain
ts = numpy.linspace(0, (Ni-1)/ai_rate, Ni)
pylab.plot(ts, y1, label='analog in')

# Get expected curve
ye = numpy.sin(2*numpy.pi*f*ts)
pylab.plot(ts, ye+2.0, label='expected')

# Plot sum to see the beating
pylab.plot(ts, ye+y1+5.0, label='sum')

pylab.legend()
pylab.xlabel('Time (s)')
pylab.ylabel('Voltage plus artificial offsets (V)')
```

Here is the result:

![image](https://user-images.githubusercontent.com/8275367/90846215-b654bd00-e335-11ea-8580-754f8dd3034a.png)

You can see there is a predictable beating pattern in the sum, suggesting the actual frequency is about 10 Hz from the expected. Also notice that the beating comes in steps that are equal in duration to the output buffer, suggesting discontinuities at the loop point. Zooming in you can really see the discontinuity in the beat pattern and the measured data:

![image](https://user-images.githubusercontent.com/8275367/90846357-f451e100-e335-11ea-8efc-8132ce11f154.png)

Meanwhile, if I set `No` to an integer multiple of 4, this problem goes away:

![image](https://user-images.githubusercontent.com/8275367/90846437-1e0b0800-e336-11ea-93ab-e973f04f9e43.png)

The obvious workaround is to restrict buffer lengths to multiples of 4, which reduces the number of frequencies that can be generated. "Minor issue", but only once you know about it! I was honestly about to give up on this device, thinking it couldn't create a reliable frequency; those hiccups were hard to find before I plotted the beat signal, so it just looked like sines going in and out of phase, as though the frequency was simply absurdly wrong (good luck trying to measure quadratures or transfer functions!).

Anyway, hope this helps (and that I'm not missing something embarrassing! :)

EDIT:
I'm on Linux Mint 19 (Ubuntu 18), with libm2k v0.2.1 and libiio v0.21.

**Comment by teoperisanu** [comment]
Hi,

we have provided a noninvasive solution for this situation, namely, a warning will notify the user about the buffer size issue (only if the logging system is enabled).

Thank you,
Teo
