### ISSUE TITLE
AnalogOut: pushRaw should not process samples

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/libm2k#24]
pushRaw method should send data directly to the DAC without any alterations. The data is scaled by -16 before being sent to the DAC.

https://github.com/analogdevicesinc/libm2k/blob/master/src/analog/private/m2kanalogout_impl.cpp#L438

https://github.com/analogdevicesinc/libm2k/blob/master/src/analog/private/m2kanalogout_impl.cpp#L267

**Comment by AlexandraTrifan** [comment]
Should be fixed with commit 1290bfbba6d381f84bedf33b96c9043f4a157f70
