### ISSUE TITLE
Triggering Capabilities/Available settings for M2K's Digital Input

### ISSUE THREAD

**Issue by xwkang2019** [analogdevicesinc/libm2k#266]
Dear Developers,

We were trying to use the digital input of M2K along with the trigger setting but after going through the API Wiki page we still have confusions over what we could or could not do with the triggering. Long time ago Alexandra kindly explained to me the triggering condition (rising/falling/any edge, high/low) and triggering level for the analog input of M2K but I am not sure if the same applies to the digital input of M2K. For example, for a scenario as shown in the figure below:
![image](https://user-images.githubusercontent.com/53637174/130016118-7f640d23-86f0-4ffd-a978-46cb5d84241d.png)
The M2K DIO 0  is seeing a square wave with 50 MHz frequency and sampling at 100 MHz, in which case it will capture 0,1,0,1...etc.
However, if we want to have control over precise where we sample (e.g. in this case we want to sample at the green instants rather than the red instants), could we accomplish such goal using the triggering?
My understanding is that the digital input of M2K can be set to trigger based on the analog in or signal at the trigger channel (T0) and from the API I can set the trigger condition to edge and level just like setting the trigger condition for receiving analog signal. The problem is, can I also set the trigger voltage level (like in analog case) so I can (as shown in the illustration) send something like a triangle pulse along with my square pulse and then set the trigger condition to rising or falling edge with the trigger level near/maybe a little less than the peak voltage of the triangle wave. With that, I should be able to get samples at all the green instants.

Thanks in advance for any insights you could offer!

**Comment by adisuciu** [comment]
It is not possible to shift the sampling point by any amount. The sampling rate is coherent with the device's internal clock. 
What you could do is provide external clock (that has the appropriate phase), and configure libm2k to use it, however on this end I think you are bandwidth limited so you can go up to as high as 20MHz.

(full disclaimer: I do software so I may be wrong on some things)
