### ISSUE TITLE
SPI Clock Rate

### ISSUE THREAD

**Issue by vsethia-adi** [analogdevicesinc/libm2k#293]
Is there any possibility to generate SPI clock rate which are not a direct descendent of 100MHz - like 30MHz, 33MHz, 40MHz in python.
If yes, let me know how to do that.

**Comment by adisuciu** [comment]
It is not possible to do that using the internal clock.
You can use an external clock (which is bandwidth limited, so you probably won't get to such high frequencies). This external clock is used for all the logic instruments (both pattern generator and logic analyzer), so you need to keep that in mind.

https://github.com/analogdevicesinc/libm2k/blob/master/bindings/python/examples/external_clocksource.py
