### ISSUE TITLE
m2k and fmcomms are products, not devices

### ISSUE THREAD

**Issue by mihaiolteanu** [analogdevicesinc/libm2k#30]
Both `m2k` and `fmcomms` appear as devices throughout the code, but they are products (as it's clearly stated on their official ADI product pages [1] [2]), available through contexts, that they themselves contain multiple devices.

Some examples,

In `contextbuilder.hpp`,
```
enum DeviceTypes {
    DevFMCOMMS,
    DevM2K,
    Other
};
```
In the folder structure,
```
libm2k/src/devices/FMCOMMS
libm2k/src/devices/M2K
```
In `enums.hpp`. Similar name to `enum DeviceTypes` from above, different contents,
```
namespace utils {
	enum DEVICE_TYPE {
		ANALOG_DEV = 1,
		DIGITAL_DEV = 2,
		NO_DEV = 3
	};
...
}
```
In the devices namespace (m2k.hpp), where it clearly inherits from a context,
so from a product, so clearly not a device,
```
namespace devices {
    class LIBM2K_API M2k : public Context
```
`Device` has a special meaning within IIO, and it _corresponds to a single hardware sensor and it provides all the information needed by a driver handling a device._ [3], or _devices are in some sense analog to digital or digital to analog converters_ [4].

Redefining already established terminology both in the Linux IIO community and in ADI's own documentation only adds unnecessary confusion and complexity for no actual gain.

[1] [m2k](https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/adalm2000.html#eb-overview)
[2] [fmcomms](https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/eval-ad-fmcomms3-ebz.html#eb-overview)
[3] [Linux kernel device terminology](https://www.kernel.org/doc/html/v4.15/driver-api/iio/core.html)
[4] [Analog Device's own terminology](https://wiki.analog.com/software/linux/docs/iio/iio)

**Comment by AlexandraTrifan** [comment]
Renamed everything related to Context in PR #41
