### ISSUE TITLE
libm2k spi functionality in python

### ISSUE THREAD

**Issue by vsethia-adi** [analogdevicesinc/libm2k#301]
I wish to know the following
1. Is there a way for me to control the CSB high pulse width for an active low chip select.?
2. Is there a way to control the first SCLK falling edge  after the chip select falling edge for the SPI_MODE_0? Similar features for other spi modes.
3. In Scopy Pattern Generator view, there is an option for bytes per frame and inter frame space for the SPI functionality. Are both features available in the libm2k module? If yes, how to access it?

**Comment by teoperisanu** [comment]
1. You cannot control directly the width of non-active CSB pulses. What you can do is to create multiple SPI sequences and then combining them manually, using the digital interface, create a new digital buffer in which the distance between them (computed by you) contains values for a non-active CS.
2. All buses (including SCLK) are computed in the back-end and cannot be altered that easy (just the parameter that are provided in the spi descriptor: frequency, pin buses, spi mode, cs polarity, bit numbering). The only way would be to create the buffer and then modify it.
3. Scopy does not use the SPI interface provided by libm2k. libm2k does not contain the concept of data frames.

All these ideas are great, but unfortunately the libm2k communication interfaces were not designed for that - they are based on an older version of no-OS interfaces; it's true that now there is a new API that provides more flexibility for these kind of things (spi_transfer: https://github.com/analogdevicesinc/no-OS/blob/master/include/no-os/spi.h). But it will take some time until they will be implemented in libm2k. Of course any contribution for the project would be much appreciated.

Thank you,
Teo
