### ISSUE TITLE
discrete values of analog out sample rate not communicated

### ISSUE THREAD

**Issue by SilvanRehm** [analogdevicesinc/libm2k#313]
the library allows arbitrary values for the sample rate, but internally only discrete values are used. 

> aout.setSampleRate(0, int(100e6))

Expectation: a Sample Rate of 100MHz
What happens: Sample Rate is 75 MHz

(There is no word in the analog out example about this behavior)

Proposals:

- raise an exception when the sample rate is not equal to what was set
- instead of setting the sample rate directly, select it with a key:
 >aout.setSampleRate(0,libm2k.SAMPLERATE_75MHz)

**Comment by AlexandraTrifan** [comment]
Hi,

The Analog Out object has a function called getAvailableSampleRates(channel_index). This will return a list of accepted values for the samplerate. 
Also, when calling 
`aout.setSampleRate(0, int(100e6))`
the function will return a value which is the value that was actually written internally.

Below is an example of usage in the python command line:

>>> m2k=libm2k.m2kOpen()
>>> aout=m2k.getAnalogOut()
>>> aout.setSampleRate(0, 1000000)
750000.0
>>> aout.setSampleRate(0, int(100e6))
75000000.0
>>> aout.getAvailableSampleRates(0)
(750.0, 7500.0, 75000.0, 750000.0, 7500000.0, 75000000.0)
>>> 

-Alexandra
