### ISSUE TITLE
Using 64-bit labview truncates 64-bit handle (address) to 32-bit

### ISSUE THREAD

**Issue by danestarija** [analogdevicesinc/libm2k#331]
![image](https://user-images.githubusercontent.com/36982573/195120389-aa5c4163-33c7-4860-adec-fc0a4f8cd7d9.png)

**Comment by AlexandraTrifan** [comment]
Hi,

I will run the setup, investigate and provide some more details here.
Which LabVIEW version are you using?

Thank you!
-Alexandra

**Comment by AlexandraTrifan** [comment]
A libm2k LabVIEW package addressing this issue was released and it is compatible with the latest libm2k release v0.8.0.
