### ISSUE TITLE
Please add Python 3.11 support 

### ISSUE THREAD

**Issue by trinamic-jh** [analogdevicesinc/libm2k#340]
Hey, 

I noticed that there is no Python wheel for Python 3.11. To maintain compatibility updated Python wheels would be necessary. 

Regards, 
JH

**Comment by AlexandraTrifan** [comment]
Hi, 

We will create a new release later this year and will include support for newer Python versions as well.

Thanks!
-Alexandra

**Comment by p-d-h** [comment]
Hello Alexandra,
We would like to use the ADALM2000 with Python in class based on Python 3.11.
Thanks Pascal

**Comment by AlexandraTrifan** [comment]
Hi,

All the necessary changes for Python 3.11 were completed but some other fixes that needed to be done pushed the release timeline. The plan is to publish the new release next week. After being published, the pypi repository will be automatically updated to contain the new artifacts.

Thank you!
-Alexandra

**Comment by AlexandraTrifan** [comment]
Hi,

libm2k v0.8.0 is now available -  https://github.com/analogdevicesinc/libm2k/releases/tag/v0.8.0
The wheels are available for download in the release page. 
The Conda packages will deliver v0.8.0 once the conda repository for libm2k gets updated and the PR is approved.
