### ISSUE TITLE
Python examples + threading or so.

### ISSUE THREAD

**Issue by karu2003** [analogdevicesinc/libm2k#358]
Where to find a python example for libm2k+threading for ADALM2000.

Thank you.
Andrew.

**Comment by AlexandraTrifan** [comment]
Hi,

All our Python examples can be found here: https://github.com/analogdevicesinc/libm2k/tree/main/bindings/python/example
I don't think we have any specific libm2k python threading examples.

Thank you!
-Alexandra

**Comment by karu2003** [comment]
It's a pity. A very useful feature. I'll try to do it, but it doesn't work for me yet.
