### ISSUE TITLE
DeviceGeneric assumes all output channels are called "voltageX"

### ISSUE THREAD

**Issue by mihaiolteanu** [analogdevicesinc/libm2k#53]
DeviceGeneric searches for all the device's channels at init. But it assumes all the output channels are of the form "voltageX" where X is from 0 to nb_channels.

In `devicegeneric_impl.cpp`

```
std::string name = "voltage" + std::to_string(i);
chn = new Channel(m_dev, name.c_str(), true);
```
But the `7c700000.axi-pulse-capture` device has an output channel named `altvoltage0`, for example.

As a result, `m_channel_list` remains empty after init, as no valid channels are discovered during the generic device initialization.

**Comment by AlexandraTrifan** [comment]
A fix for this was added in PR #62 and merged into master.
libm2k should not assume that channels are all called "voltage". 
The added fix scans all the channels based on their index and sorts them. This way, the DeviceGeneric will be able to handle any channels, not just "voltage" ones.
