### ISSUE TITLE
Multiple errors while using generic devices from a context

### ISSUE THREAD

**Issue by mihaiolteanu** [analogdevicesinc/libm2k#57]
1. Open a Lidar context,
```
Context *context = ContextBuilder::contextOpen("ip:10.48.65.139");
```
2. Get all the analogIn devices,
```
auto all_analog_in = context->scanAllAnalogIn();

for (auto i = all_analog_in.begin(); i != all_analog_in.end(); ++i) {
    cout << *i << "\n";
}
```
**Result** (the devices are recognized, all good): 
```
axi-ad9094-hpc
ad7091
```
3. Try to get an analogIn device and print it's name (same as above, only each device individually):
```
libm2k::analog::GenericAnalogIn* dev_in = context->getAnalogIn("ad7091");
cout << dev_in->getDeviceName();
```
**Result**: 
```
Compilation segmentation fault (core dumped)
```

4. Try the same but with index instead of a string,
```
libm2k::analog::GenericAnalogIn* dev_in = context->getAnalogIn(0);
cout << dev_in->getDeviceName();
```
**Result**: "" (empty string)

5. Ignore the above and try to get some samples,
```
dev_in->getSamples(100);
```
**Result**: 
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  ERR: Invalid argument - Buffer: No channel enabled for RX buffer

Compilation aborted (core dumped)
```

How are these generic classes to be used? Should they not be used directly like that? Should one derive from these classes and implement additional functionality for them to work? At the moment it doesn't seem like I can do much with them, except reading their string representation.

Edit: Last error seems to be "no channel enabled". That seems obvious. I'll try to redo that last example.

Edit2:
6. enable at least a channel before trying to refill the buffer
```
dev_in->enableChannel(1, true);
dev_in->getSamples(100);
```
**Result**
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  ERR: Invalid argument - Buffer: Cannot refill RX buffer
```
I've tried with both devices, index 0 and index 1 since I'm not sure which is which and tried to enable different channels. Same result.

**Comment by AlexandraTrifan** [comment]
Can you retest this with the latest master version? 
The "getDeviceName" issue should no longer appear.
Also, since the channel scanning mechanism changed, the buffer and device will correctly scan all the channels (not just "voltage" ones). I think the getSamples failing is related to this previous channel issue.
