### ISSUE TITLE
getSamplesRawInterleaved enables all channels in the m_channel_list before creating a buffer

### ISSUE THREAD

**Issue by mihaiolteanu** [analogdevicesinc/libm2k#58]
In `buffer_impl.cpp`,
```
for (auto chn : m_channel_list) {
    chn->enableChannel(true);
}
```
getSamples should only read from the channels that the user enabled.
But this code enables all the channels before reading any samples. Is this a mistake or is there a purpose behind this?

**Comment by AlexandraTrifan** [comment]
Fix and explanation in issue #59 and PR #63.
