### ISSUE TITLE
getSamplesRawInterleaved (re)enables all the channels that were found to be enabled

### ISSUE THREAD

**Issue by mihaiolteanu** [analogdevicesinc/libm2k#59]
In `buffer_impl.cpp`,
```
for (unsigned int i = 0; i < m_channel_list.size(); i++) {
    m_channel_list.at(i)->enableChannel(channels_enabled.at(i));
}
```
This (re)enables all the channels based on a list of (already) enabled channels AFTER the samples have been read from the buffer.
Is this a mistake or is there a purpose behind it?

**Comment by AlexandraTrifan** [comment]
The fix for this was merged into master with PR #63. 
All the channels were enabled before refilling because that's how M2K needs this done.
However, the location of the enabling process should be located in M2KAnalogIn, not in the Buffer implementation, which is supposed to be generic.
