### ISSUE TITLE
iio_buffer_refill in getSamplesRawInterleaved fails with iiolib error "Too few arguments in function call"

### ISSUE THREAD

**Issue by mihaiolteanu** [analogdevicesinc/libm2k#60]
With setup from #57, the return values from this call,
```
ssize_t ret = iio_buffer_refill(m_buffer);
```
is an error code for "Too few arguments in function call."

I have no clue where or what the problem might be. Maybe in the buffer init phase?!
Any ideas?

**Comment by AlexandraTrifan** [comment]
@mihaiolteanu  Does this still happen? Can we close this?
