### ISSUE TITLE
DAC seems to be worked wrong in lower sampling frequency

### ISSUE THREAD

**Issue by goediy** [analogdevicesinc/libm2k#73]
Hello

I noticed a problem when I tried to get 1KHz of analog sin wave using function generater with Python program. The problem is that the frequency of the output sin wave is differ depending on the setting for sampling frequency of DAC. The code is as follows:
```
import libm2k
import matplotlib.pyplot as plt
import numpy as np

ctx=libm2k.m2kOpen()
if ctx is None:
	print("Connection Error: No ADALM2000 device available/connected to your PC.")
	exit(1)

INFS = 100000    # 100KHz -> 1/1000 decimation

#OUTFS = 75000000 # 75MHz  -> no interpolation
OUTFS = 7500000  # 7.5MHz -> 10x interpolation
#OUTFS = 750000   # 750KHz -> 100x interpolation
#OUTFS = 75000     # 75KHz -> 1000x interpolation

TESTFREQ = 1000
TESTLEN = 50000

ctx.calibrateADC()
ctx.calibrateDAC()

ain=ctx.getAnalogIn()
aout=ctx.getAnalogOut()

ain.enableChannel(0,True)
ain.setSampleRate(INFS)
ain.setRange(0,-10,10)

aout.setSampleRate(0, OUTFS)
aout.enableChannel(0, True)

period_out = OUTFS/TESTFREQ
x = np.linspace(0,2*np.pi,period_out,endpoint=False)
sig = np.sin(x)
buf = [sig]

aout.setCyclic(True)
aout.push(buf)

period_in = int(INFS/TESTFREQ)
data = ain.getSamples(TESTLEN)
plt.plot(data[0][0::period_in])
plt.ylim(-1.5,1.5)
plt.show()

libm2k.contextClose(ctx)
```
I wired W1->1+ and GND->1-. Then I ran this program with setting OUTFS to 75MHz or 7.5MHz I got DC on graph. Otherwise, sine wave appears in the graph. As the ADC sampling frequency is fixed, this means the frequency of sin wave changed when lower sampling frequency for DAC. Also can be observed this by using FFT.

Is there any solution about above things?

![7 5MHz](https://user-images.githubusercontent.com/54144565/69907913-743fc000-1422-11ea-9c13-4a3cce4484ce.png)
![750KHz](https://user-images.githubusercontent.com/54144565/69907917-891c5380-1422-11ea-81e4-c27bb603dab7.png)

**Comment by adisuciu** [comment]
We answered your question on EZ - https://ez.analog.com/adieducation/university-program/f/q-a/119343/adalm2000-dac-seems-to-be-worked-wrong-when-below-frequency-750khz
